Bartalamey
bboyzlodey/ecoproject pull request #12
Opened 2021-01-24 17:56 UTC by Bartalameu

2021-01-25 18:16 UTC, bboyzlodey reviewed
Уже лучше!

В общем создание копий, или изменение файлов, которые никак не влияют на работу приложения - это ненужная процедура. Ты можешь у себя делать, что хочешь. Но в пул реквест отправлять не нужно

Если ты хочешь поменять название файла, то это должно быть осознано и оправдано

2021-01-25 18:16 UTC, bboyzlodey commented on app/src/main/AndroidManifest.xml
> +			<intent-filter>
Это для тестов? Удали

2021-01-25 18:16 UTC, bboyzlodey commented on app/src/main/res/values/colors.xml
> +    <color name="colorPrimaryDark">#3700B3</color>
Зачем ты поменял цвет?!)

2021-01-25 18:16 UTC, bboyzlodey commented on app/src/main/res/values/strings.xml
> +    <string name="How_can_i_help">Как я могу помочь?</string>
Не надо переводить строку на английский и писать ее как name
Name - отображает суть, а не значение

2021-01-25 18:16 UTC, bboyzlodey commented on app/src/main/res/values/strings.xml
> +    <string name="How_can_i_help">Как я могу помочь?</string>
header_eco_article - как пример

2021-01-25 18:16 UTC, bboyzlodey commented on app/src/main/res/layout/advice_view.xml
> +<?xml version="1.0" encoding="utf-8"?>
Это не вью, а item для ресайклера
app/src/main/res/layout/advice_view.xml - это название макета для инфлейта кастомной вьюшки
item_advice - хорошо сюда подойдет

2021-01-25 18:16 UTC, bboyzlodey commented on app/src/main/res/layout/activity_course_card.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Зачем нужно было трогать этот файл?

2021-01-25 18:16 UTC, bboyzlodey commented on app/src/main/res/layout/activity_eco_cards.xml
> +            <com.google.android.material.appbar.AppBarLayout
Ты изменил файл и нигде его не используешь в своем коде. Зачем тогда это комитить?

2021-01-25 18:16 UTC, bboyzlodey commented on app/src/main/res/layout/activity_eco_cards.xml
> +                        android:onClick="onBackBtn"
Так мы больше не пишем :)

2021-01-25 18:16 UTC, bboyzlodey commented on app/src/main/java/skarlat/dev/ecoproject/adapter/TipsAdapter.kt
> +        cards.addAll(card)
Перед добавлением в лист, его надо очистить

2021-01-25 18:16 UTC, bboyzlodey commented on app/src/main/java/skarlat/dev/ecoproject/adapter/TipsAdapter.kt
> +    private val inflater: LayoutInflater = LayoutInflater.from(context)
Да, в моем примере написано так...
Но так делать нельзя
Не нужно передавать контекст в адаптер

Контекст пожно взять у вью или у парента

2021-01-25 18:16 UTC, bboyzlodey commented on app/src/main/java/skarlat/dev/ecoproject/adapter/TipsAdapter.kt
> +
val layoutInflater = LayoutInflater.from(parent.context)

2021-01-25 18:16 UTC, bboyzlodey commented on app/src/main/java/skarlat/dev/ecoproject/adapter/TipsAdapter.kt
> +         interface OnAdviceListener {
Интерфейс лишний

2021-01-25 18:16 UTC, bboyzlodey commented on app/src/main/java/skarlat/dev/ecoproject/adapter/TipsAdapter.kt
> +         val clickListener = itemView.setOnClickListener(this )
Что будет храниться в переменной? Оно тебе как-то в дальнешем понадобится?
Для иницилизации есть блок `init {
}`

2021-01-25 18:16 UTC, bboyzlodey commented on app/src/main/java/skarlat/dev/ecoproject/adapter/TipsAdapter.kt
> +    private var cards = arrayListOf<Any>()
У нас карточки или типсы? Зачем нам изменяемая переменная? Мы ее изменяем как-то?

2021-01-26 15:46 UTC, Bartalameu commented on app/src/main/res/values/colors.xml
> +    <color name="colorPrimaryDark">#3700B3</color>
честно не могу вспомнить, скорее всего забыл вернуть как было

2021-01-26 15:47 UTC, Bartalameu commented on app/src/main/res/values/strings.xml
> +    <string name="How_can_i_help">Как я могу помочь?</string>
писать гаммотные коммиты, название переменных и тд, для меня это отдельный вид исскуства, я пока в этом оч плох, но я понял

2021-01-26 15:49 UTC, Bartalameu commented on app/src/main/res/layout/activity_course_card.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
опять же , забыл вернуть в исходное положение, прости

2021-01-26 15:51 UTC, Bartalameu commented on app/src/main/java/skarlat/dev/ecoproject/adapter/TipsAdapter.kt
> +         interface OnAdviceListener {
без интерфейса не знаю как сделать, если можно без то поищу

2021-01-26 15:51 UTC, Bartalameu commented on app/src/main/java/skarlat/dev/ecoproject/adapter/TipsAdapter.kt
> +         val clickListener = itemView.setOnClickListener(this )
долбаный kotlin cэр

2021-01-26 15:53 UTC, Bartalameu commented on app/src/main/java/skarlat/dev/ecoproject/adapter/TipsAdapter.kt
> +    private var cards = arrayListOf<Any>()
поидее нет, каждый раз же будем в эту переменную новый типсы и EcoCard засовывать, опять моя не грамотность судя всего

2021-01-27 10:14 UTC, bboyzlodey commented on app/src/main/res/values/strings.xml
> +    <string name="How_can_i_help">Как я могу помочь?</string>
Так мы для этого (и не только для этого) делаем код ревью)

2021-01-27 10:55 UTC, bboyzlodey commented on app/src/main/java/skarlat/dev/ecoproject/adapter/TipsAdapter.kt
> +        val card_title: TextView = itemView.findViewById(R.id.card_title)
Имена переменных пишутся в верблжьем стиле. Т.е.:
cardTitle

2021-01-27 14:28 UTC, Bartalameu commented on app/src/main/java/skarlat/dev/ecoproject/adapter/TipsAdapter.kt
> +        val card_title: TextView = itemView.findViewById(R.id.card_title)
нехочу хвастаться, но единственное мое личное достижение, это то что я вчера , еще до твоего ответа так исправил )))

2021-01-30 17:34 UTC, closed without merging

2021-01-30 18:31 UTC, bboyzlodey reviewed
1) Приложение крашится при открытии карточки
2) Некоторые старые замечания остались актуальными (пожалуйста повнимательнее)
3) Рекомендую смотреть уже мной написанные примеры и внимательно их изучать

На будущее: если хочешь что-то переписать на котлин из существующего, то сначала скажи мне. Я сделаю это сам, а ты сделаешь пулл (обновление) из моей ветки. Это для того, чтобы не было такого, что у тебя код на котлин, а у меня тот же активити на java

2021-01-30 18:31 UTC, bboyzlodey commented on app/src/main/java/skarlat/dev/ecoproject/adapter/TipsAdapter.kt
> +        cards.addAll(card)
?

2021-01-30 18:31 UTC, bboyzlodey commented on app/src/main/java/skarlat/dev/ecoproject/activity/CardActivity.kt
> +        adapter.clearList()
Очистка листа должна просходить внутри адаптера. Адаптер должен самостоятельно очистить лист. Логику очищения листа добавь в тело метода `submitList`

2021-01-30 18:31 UTC, bboyzlodey commented on app/src/main/java/skarlat/dev/ecoproject/adapter/TipsAdapter.kt
> +    var onItemClick: ((EcoCard) -> Unit)? = null
Уже лучше
Но тут нам нужна не `var`, а `val`. Предпочтительнее использовать `val`

Ты можешь написать такой конструктор для адаптера: `class TipsAdapter( private val onOpenArticleClicked: ((EcoCard) -> Unit)) ...`

2021-01-30 18:31 UTC, bboyzlodey commented on app/src/main/java/skarlat/dev/ecoproject/adapter/TipsAdapter.kt
> +      cards.clear()
Перенеси в тело мето метода `submitList`

2021-01-30 18:31 UTC, bboyzlodey commented on app/src/main/java/skarlat/dev/ecoproject/adapter/TipsAdapter.kt
> +        holder.description.text = "Test text Test text !!!!!!"
?

2021-01-30 18:31 UTC, bboyzlodey commented on app/src/main/res/values/strings.xml
> +    <string name="next_card_open">Следующая карточка открыта!</string>
Это зачем? У нас такого в ui

2021-01-30 18:31 UTC, bboyzlodey commented on app/src/main/java/skarlat/dev/ecoproject/activity/CardActivity.kt
> +lateinit var ecoCard: EcoCard
1) Модификатор доступа. Если поле не используется в другом классе ставь `private`
2) `lateinit var` - это очень плохая практика, которая приводит к вылетам. Например, при открытии карточки вылетает этот exceprion:
Эмулятор Pixel 2 API 29
`2021-01-30 21:16:47.407 9850-9850/skarlat.dev.ecoproject E/AndroidRuntime: FATAL EXCEPTION: main
    Process: skarlat.dev.ecoproject, PID: 9850
    java.lang.RuntimeException: Unable to start activity ComponentInfo{skarlat.dev.ecoproject/skarlat.dev.ecoproject.activity.CardActivity}: kotlin.UninitializedPropertyAccessException: lateinit property card has not been initialized
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: kotlin.UninitializedPropertyAccessException: lateinit property card has not been initialized
        at skarlat.dev.ecoproject.activity.CardActivityKt.getCard(CardActivity.kt:22)
        at skarlat.dev.ecoproject.activity.CardActivity.initiList(CardActivity.kt:57)
        at skarlat.dev.ecoproject.activity.CardActivity.onCreate(CardActivity.kt:44)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) `

2021-01-30 18:31 UTC, bboyzlodey commented on .idea/shelf/Uncommitted_changes_before_Checkout_at_12_25_20_10_17_PM__Default_Changelist_.xml
> +  <option name="DESCRIPTION" value="Uncommitted changes before Checkout at 12/25/20 10:17 PM [Default Changelist]" />
Все, что выше не нужно включать в пул реквест!

2021-01-30 18:31 UTC, bboyzlodey commented on app/src/main/res/layout/activity_eco_cards.xml
> +                <Button
Кнопку тоже в ресайклер

2021-01-30 18:31 UTC, bboyzlodey commented on app/src/main/res/layout/activity_eco_cards.xml
> +        <androidx.core.widget.NestedScrollView
NestedScrollView не должно быть. Идея как раз в том, что мы избавляется от него и переносим все в ресайклер.

2021-01-30 18:37 UTC, bboyzlodey requested changes
Пожалуйста, там где исправляешь, пометь, что исправлено

2021-01-30 18:39 UTC, bboyzlodey commented
isqua.ru › blog › 2017/04/12
Все результаты
Как открыть пулл-реквест в Github и не облажаться - isqua

2021-01-31 18:05 UTC, Bartalameu commented on app/src/main/java/skarlat/dev/ecoproject/adapter/TipsAdapter.kt
> +    var onItemClick: ((EcoCard) -> Unit)? = null
не понимаю как это работает, тяжело для меня такое

2021-01-31 20:10 UTC, Bartalameu commented on app/src/main/java/skarlat/dev/ecoproject/adapter/TipsAdapter.kt
> +        holder.description.text = "Test text Test text !!!!!!"
не понял что не так

2021-02-01 09:10 UTC, bboyzlodey commented on app/src/main/java/skarlat/dev/ecoproject/adapter/TipsAdapter.kt
> +    var onItemClick: ((EcoCard) -> Unit)? = null
https://kotlinlang.ru/docs/reference/classes.html - Заголовок контрукторы
https://kotlinlang.ru/docs/reference/basic-syntax.html - Опеределие внутренних переменных